DefaultContentLanguage = "en"
baseurl = "/"
canonifyurls = true
disqusShortname = "www-coastsystems-net"
metaDataFormat = "toml"
paginate = 10
paginatePath = "page"
theme = "hugo-bootstrap-premium"
#theme = "acadien-hugo-theme"
[Languages.en]
copyright = "(c) 2018 Boyd Kelly"
languageCode = "en"
languageName = "English"
title = "Coast Business Technologies"
weight = 1
[[Languages.en.menu.main]]
identifier = "post"
name = "Blog"
pre = ""
url = "/post/"
weight = 6
[[Languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"
weight = 1
[[Languages.en.menu.main]]
identifier = "tech"
name = "Technology"
url = "/topics/Technology"
weight = 2
[[Languages.en.menu.main]]
identifier = "aef"
name = "English in French"
url = "/topics/English in French"
weight = 3
[[Languages.en.menu.main]]
identifier = "jula"
name = "Julakan"
url = "/topics/Julakan"
weight = 4
[Languages.fr]
copyright = "(c) 2018 Boyd Kelly"
languageCode = "fr"
languageName = "Français"
title = "Coast Business Technologies"
weight = 2
[[Languages.fr.menu.main]]
identifier = "post"
name = "Blog"
pre = ""
url = "/fr/post/"
weight = 6
[[Languages.fr.menu.main]]
identifier = ""
name = "À propos"
pre = "<i class='fa fa-road'> </i>"
url = "/fr/about"
weight = 1
[[Languages.fr.menu.main]]
identifier = "tech"
name = "Technologie"
url = "/fr/sujets/technologie"
weight = 2
[[Languages.fr.menu.main]]
identifier = "aef"
name = "Anglais en français"
url = "/fr/sujets/anglais en français"
weight = 3
[[Languages.fr.menu.main]]
identifier = "jula"
name = "Julakan"
url = "/fr/sujets/julakan"
weight = 4
[Languages.fr.taxonomies]
tag = "marques"
topic = "sujets"
[author]
email = "bkelly@coastsystems.net"
name = "Boyd Kelly"
[blackfriday]
angledQuotes = true
extensionmask = []
extensions = []
fractions = false
hrefTargetBlank = false
latexDashes = true
plainIdAnchors = true
[params]
brand_image = "/images/brand.png"
bitbucket = ""
bootswatchtheme = "slate"
brand = "Coast Business Technologies"
#customCSS = ["/css/style_custom.css"]
customJS = []
facebook = ""
flattr = ""
github = "www.github.com/boydkelly"
googleAnalytics = "UA-7938441-2"
googleplus = "Myprofile"
highlight = "default"
#home = "about"
linkedin = "www.linkedin.com/in/boydkelly"
mailmunchid = ""
mathjax = ""
showRightSidebar = true
sumomeid = ""
switchlang = true
tagline = "Technology, Language, Accounting"
twitter = "www.twitter.com/boydkelly"
youtube = ""
[permalinks]
code = "/:filename/"
post = "/:year/:month/:day/:filename/"
[taxonomies]
tag = "tags"
topic = "topics"
